let extension_id = 'dreamforgeturbowarpextensionbuilder';

(function (Scratch) {
    'use strict';

    class ExtensionDefinitionBlocks {
        constructor(runtime) {
            this.runtime = runtime;
            this.generatedCode = "";
            this.presetCode = `// This code is generated by the Turbowarp Extension Builder extension by dreamForge. You can edit the blocks in the workspace to change this code.\n\n`; // You can use this variable to preset some code that you want to be included in every block, for example if you want to always include a certain variable or function definition in every block.
        }

        getInfo() {
            return {
                id: extension_id,
                name: 'Extension Definition Blocks',
                color1: '#9595eb', // Main block color
                blocks: [
                    {
                        opcode: 'defineExtensionHat',
                        blockType: Scratch.BlockType.HAT,
                        text: 'define turbowarp extension [NAME]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'MyCoolAndAwesomeExtension'
                            }
                        }
                    },
                    {
                        opcode: 'generateExtensionMetaData',
                        blockType: Scratch.BlockType.CONDITIONAL,
                        text: 'Define [DEFINITIONTYPE]',
                        branchCount: 1, // This is the magic property
                        arguments: {
                            DEFINITIONTYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'definitionTypes' // Must match the key in the menus object
                            }
                        }
                    },
                    {
                        opcode: 'defineArguments',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'Define argument [NAME] as [TYPE] with defaultValue [DEFAULT]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Argument Name'
                            },
                            TYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'argumentTypes' // Must match the key in the menus object
                            },
                            DEFAULT: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            }
                        }
                    },
                    {
                        opcode: 'setMetaData',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'set [METATAG] to [VALUE]',
                        arguments: {
                            METATAG: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'metaData' // Must match the key in the menus object
                            },
                            VALUE: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            }
                        }
                    },
                    {
                        opcode: 'buildBlockType',
                        blockType: Scratch.BlockType.REPORTER,
                        text: 'block type[TYPE]',
                        arguments: {
                            TYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'blockTypes' // Must match the key in the menus object
                            }
                        }
                    },
                ],
                menus: {
                    metaData: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'ID', value: 'id' },
                            { text: 'Name', value: 'name' },
                            { text: 'Block Color', value: 'color1' },
                            { text: 'Hover Color', value: 'color2' },
                            { text: 'Function', value: 'opcode' },
                            { text: 'Type', value: 'blockType' },
                            { text: 'Text', value: 'text' },
                            { text: 'Branch Count', value: 'branchCount' }
                        ]
                    },
                    blockTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Command', value: 'Scratch.BlockType.COMMAND' },
                            { text: 'Reporter', value: 'Scratch.BlockType.REPORTER' },
                            { text: 'Boolean', value: 'Scratch.BlockType.BOOLEAN' },
                            { text: 'Conditional', value: 'Scratch.BlockType.CONDITIONAL' },
                            { text: 'Loop', value: 'Scratch.BlockType.LOOP' },
                            { text: 'Hat', value: 'Scratch.BlockType.HAT' },
                            { text: 'Event', value: 'Scratch.BlockType.EVENT' }
                        ]
                    },
                    argumentTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'String', value: 'Scratch.ArgumentType.STRING' },
                            { text: 'Number', value: 'Scratch.ArgumentType.NUMBER' },
                            { text: 'Boolean', value: 'Scratch.ArgumentType.BOOLEAN' }
                        ]
                    },
                    definitionTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Extension meta data', value: 'emd' },
                            { text: 'Extension blocks', value: 'eb' },
                            { text: 'Block meta data', value: 'bmd' },
                            { text: 'Block arguments', value: 'bargs' },
                        ]
                    }
                }
            };
        }

        /**
         * This helper looks at the blocks snapped under the Hat
         * and turns them into a JS string.
         */
        transpile(currentId, target) {
            let lines = [];

            while (currentId) {
                const block = target.blocks.getBlock(currentId);
                const opcode = block.opcode;

                if (block.fields && block.fields.NUM) {
                    return block.fields.NUM.value; // Returns "2"
                }
                if (block.fields && block.fields.TEXT) {
                    return `"${block.fields.TEXT.value}"`; // Returns "Hello"
                }

                let substackId = null;
                try {
                    substackId = block.inputs.SUBSTACK ? block.inputs.SUBSTACK.block : null;
                } catch (e) {
                    console.error(`Error processing block ${opcode}:`, e);
                }

                // Helper to get a clean value for any input
                const getVal = (name) => this.resolveInput(block, name, target);

                switch (opcode) {
                    case `${extension_id}_setMetaData`:
                        const tag = block.fields.METATAG.value;
                        const val = getVal('VALUE');
                        // Formatting for your JSON/Object view
                        lines.push(`  ${tag}: ${val},`);
                        break;

                    case `${extension_id}_getArgumentValue`:
                        const argName = getVal('NAME').replaceAll('"', ''); // Remove quotes if it's a string
                        return `args.${argName}`; // This allows users to get the value of an argument in their code blocks by using the "get value of argument" block and specifying the argument name.
                        break;

                    case `${extension_id}_generateExtensionMetaData`:
                        const definitionType = block.fields.DEFINITIONTYPE.value;

                        this.buildDefinition(definitionType, lines, substackId, target);
                        break;

                    case `${extension_id}_buildBlockType`:
                        lines.push(block.fields.TYPE.value);
                        break;

                    case `${extension_id}_defineArguments`:
                        let arg_type = block.fields.TYPE.value;
                        let arg_default = getVal('DEFAULT');
                        let arg_name = getVal('NAME');

                        lines.push(arg_name + `: {`);
                        lines.push(`  type: ${arg_type},`);
                        lines.push(`  defaultValue: ${arg_default}`);
                        lines.push(`}`);
                        break;

                    case `${extension_id}_checkFunctionAvailability`:
                        const functionName = getVal('NAME');
                        lines.push(`!String(this.runtime.getOpcodeFunction('${functionName}')) === 'undefined'\n`);
                        break;

                    case `${extension_id}_executeBranchBlocks`:
                        const actionType = block.fields.ACTIONTYPE.value; // "loop" or "execute"
                        const branchNumber = getVal('BRANCHNUMBER'); // 1, 2, or 3
                        
                        lines.push(`util.startBranch(${branchNumber}, ${actionType == 'loop'});`); // Start the specified branch

                        break;
                    default:
                        const scratchVMTarget = Scratch.vm.runtime.getEditingTarget();

                        if (this.presetCode.includes(`this.${opcode} =`)) break; // If the preset code already contains this opcode, skip it to avoid duplicates

                        this.presetCode += `this.${opcode} = this.runtime.getOpcodeFunction('${opcode}');\n`;
                        // remove all "" so that functions will still work.
                        lines.push(`
                            await this.${opcode}(${this.getBlockArguments(block, target).replaceAll('"', ' ')}, util);
                            `);
                }

                currentId = target.blocks.getNextBlock(currentId);
            }
            return lines.join('\n');
        }

        isReporter(opcode) {
            // Get the block definition from the runtime
            const blockDef = Scratch.vm.runtime.getBlocksXML().find(b => b.opcode === opcode);

            // Check if it's a reporter (round) or a boolean (hexagonal)
            // These are the blocks that return values rather than executing 'next' blocks
            return blockDef && (blockDef.blockType === 'reporter' || blockDef.blockType === 'boolean');
        }

        getBlockArguments(block, target) {
            const args = {};
            for (const inputName in block.inputs) {
                const input = block.inputs[inputName];

                // Check if the input is a simple value (shadow) or another block (reporter)
                if (input.shadow && !input.block) {
                    // It's a direct value like a number or string
                    const value = target.blocks.getBlock(input.shadow).fields.VALUE.value;
                    args[inputName] = JSON.stringify(value); // JSON.stringify adds quotes to strings automatically
                } else if (input.block) {
                    // It's a nested reporter block (e.g., 'distance to mouse')
                    // You would recursively call a 'generateCode' function here
                    let transpiledCode = this.transpile(input.block, target).replaceAll('\n', '').trim(); // Recursively transpile the nested block and clean up the code
                    if (transpiledCode[0] === '"' && transpiledCode[transpiledCode.length - 1] === '"') {
                        transpiledCode = transpiledCode.replaceAll('"', "'"); // Convert double quotes to single quotes for string literals to avoid issues in the generated code when "" are removed
                    }
                    args[inputName] = transpiledCode.replace(';', ''); // remove semicolons to avoid issues in the generated code when ";" are removed. This is a bit hacky but it allows users to write blocks that return values without worrying about semicolons breaking their code.
                    console.log(transpiledCode);
                }
            }
            return JSON.stringify(args); // Convert the args object to a string for code generation
        }

        buildDefinition(definitionType, lines, substackId, target) {
            switch (definitionType) {
                case 'emd':
                    lines.push(`  getInfo() {`);
                    lines.push(`    return {`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`    };`);
                    lines.push(`  }`);
                    break;

                case 'eb':
                    lines.push(`blocks: [`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`]`);
                    break;

                case 'bmd':
                    lines.push(`{`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`}`);
                    break;

                case 'bargs':
                    lines.push(`arguments: {`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`}`);
                    break;

                default:
                    lines.push(`// Unknown definition type: ${definitionType}`);
            }
        }

        resolveInput(parentBlock, inputName, target) {
            const input = parentBlock.inputs[inputName];
            if (!input || !input.block) return 'null';

            const inputBlock = target.blocks.getBlock(input.block);

            // 1. Check for Shadow Blocks (Simple inputs)
            // Opcode 'text' is the white bubble for strings
            // Opcode 'math_number' is the white bubble for numbers
            if (inputBlock.opcode === 'text') {
                return `"${inputBlock.fields.TEXT.value}"`;
            }
            if (inputBlock.opcode === 'math_number') {
                return inputBlock.fields.NUM.value;
            }

            // 2. Check for Reporter Blocks (e.g. "x position", "my variable")
            // If it's a real block, transpile it to get its "code" representation
            return this.transpile(input.block, target).trim();
        }

        updateCode(args, util) {
            const target = util.target;
            const allBlocks = target.blocks._blocks;

            this.presetCode = ''; // Reset preset code on each update to avoid duplicates

            // 1. Find our "Define" Hat block in the workspace
            let hatId = null;
            let opcode_hats = [];
            for (const id in allBlocks) {
                if (allBlocks[id].opcode === `${extension_id}_defineExtensionHat`) {
                    if (!hatId) {
                        hatId = id;
                    }
                } else if (allBlocks[id].opcode === `${extension_id}_defineBlockFunction`) {
                    opcode_hats.push(id);
                }
            }

            if (!hatId) {
                this.generatedCode = "// Please place the 'define' hat block!";
                return;
            }

            // 2. Get the name from the hat block's inputs
            const nameBlockId = allBlocks[hatId].inputs.NAME.block;
            const extensionName = allBlocks[nameBlockId].fields.TEXT.value || "MyExtension";

            // 3. Generate the class string
            const body = this.transpile(target.blocks.getNextBlock(hatId), target); // pass the hat id here instead of in the transpile function so we ca nreuse the transpile function

            let opcode_body = '';
            opcode_hats.forEach(hatId => {
                const opcode_name_block_id = allBlocks[hatId].inputs.OPCODENAME.block;
                const opcode_name = allBlocks[opcode_name_block_id].fields.TEXT.value || "opcode_name";

                const hat_body = this.transpile(target.blocks.getNextBlock(hatId), target);
                opcode_body += `\n async ${opcode_name} (args, util) {\n${hat_body}\n  }\n`;
            });

            this.generatedCode = `class ${extensionName} {\n  constructor(runtime) {\n    this.runtime = runtime;\n ${this.presetCode} \n  }\n ${body}\n \n ${opcode_body}\n\n}\n Scratch.extensions.register(new ${extensionName}(Scratch.vm.runtime));`;
            console.log(this.generatedCode);
        }

        defineExtensionHat(args, util) {
            this.updateCode(args, util); // allows the user to press the green flag to update and print the generated code.
        }

    }

    class extensionCodeBlocks {
        constructor(runtime) {
            this.runtime = runtime;
            this.generatedCode = "";
            this.presetCode = `// This code is generated by the Turbowarp Extension Builder extension by dreamForge. You can edit the blocks in the workspace to change this code.\n\n`; // You can use this variable to preset some code that you want to be included in every block, for example if you want to always include a certain variable or function definition in every block.
        }

        getInfo() {
            return {
                id: extension_id,
                name: 'Extension Code Blocks',
                color1: '#725ca5', // Main block color
                blocks: [
                    {
                        opcode: 'defineBlockFunction',
                        blockType: Scratch.BlockType.HAT,
                        text: 'Define block opcode [OPCODENAME]',
                        arguments: {
                            OPCODENAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'opcode_name'
                            }
                        }
                    },
                    {
                        opcode: 'getArgumentValue',
                        blockType: Scratch.BlockType.REPORTER,
                        text: 'get value of argument[NAME]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'ARGUMENTNAME'
                            }
                        }
                    },
                    {
                        opcode: 'checkFunctionAvailability',
                        blockType: Scratch.BlockType.BOOLEAN,
                        text: 'check if function [NAME] is available',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'ARGUMENTNAME'
                            }
                        }
                    },
                    {
                        opcode: 'executeBranchBlocks',
                        blockType: Scratch.BlockType.COMMAND,
                        text: "[ACTIONTYPE] branch [BRANCHNUMBER]'s blocks",
                        arguments: {
                            ACTIONTYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'loopBranch' // Must match the key in the menus object
                            },
                            BRANCHNUMBER: {
                                type: Scratch.ArgumentType.NUMBER,
                                defaultValue: 1
                            }
                        }
                    }
                ],
                menus: {
                    loopBranch: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Loop', value: 'loop' },
                            { text: 'Execute', value: 'execute' },
                        ]
                    },
                }
            };
        }

        executeBranchBlocks () {
            return false; // The actual execution of the blocks is handled in the generated code, this block just serves as a trigger for users to indicate they want to execute branch blocks and to specify which branch number they want to execute.
        }

        checkFunctionAvailability() {
            return false;
        }

        defineBlockFunction() {
            return false;
        }

    }

    Scratch.extensions.register(new ExtensionDefinitionBlocks());
    Scratch.extensions.register(new extensionCodeBlocks());
})(Scratch);    