let extension_id = 'dreamforgeturbowarpextensionbuilder';

(function (Scratch) {
    'use strict';

    class ExtensionDefinitionBlocks {
        constructor(runtime) {
            this.runtime = runtime;
            this.generatedCode = "";
            this.presetCode = `// This code is generated by the Turbowarp Extension Builder extension by dreamForge. You can edit the blocks in the workspace to change this code.\n\n`; // You can use this variable to preset some code that you want to be included in every block, for example if you want to always include a certain variable or function definition in every block.
        }

        getInfo() {
            return {
                id: extension_id,
                name: 'Extension Definition Blocks',
                color1: '#9595eb', // Main block color
                blocks: [
                    {
                        opcode: 'defineExtensionHat',
                        blockType: Scratch.BlockType.HAT,
                        text: 'define turbowarp extension [NAME]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'MyCoolAndAwesomeExtension'
                            }
                        }
                    },
                    {
                        opcode: 'generateExtensionMetaData',
                        blockType: Scratch.BlockType.CONDITIONAL,
                        text: 'Define [DEFINITIONTYPE]',
                        branchCount: 1, // This is the magic property
                        arguments: {
                            DEFINITIONTYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'definitionTypes' // Must match the key in the menus object
                            }
                        }
                    },
                    {
                        opcode: 'setMetaData',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'set [METATAG] to [VALUE]',
                        arguments: {
                            METATAG: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'metaData' // Must match the key in the menus object
                            },
                            VALUE: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            }
                        }
                    },
                ],
                menus: {
                    metaData: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'ID', value: 'id' },
                            { text: 'Name', value: 'name' },
                            { text: 'Block Color', value: 'color1' },
                            { text: 'Hover Color', value: 'color2' },

                        ]
                    },
                    definitionTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Extension meta data', value: 'emd' },
                        ]
                    }
                }
            };
        }

        /**
         * This helper looks at the blocks snapped under the Hat
         * and turns them into a JS string.
         */
        transpile(currentId, target) {
            const allBlocks = target.blocks._blocks;

            let lines = [];

            while (currentId) {
                const block = target.blocks.getBlock(currentId);
                const opcode = block.opcode;

                if (block.fields && block.fields.NUM) {
                    return block.fields.NUM.value; // Returns "2"
                }
                if (block.fields && block.fields.TEXT) {
                    return `"${block.fields.TEXT.value}"`; // Returns "Hello"
                }

                let substackId = null;
                try {
                    substackId = block.inputs.SUBSTACK ? block.inputs.SUBSTACK.block : null;
                } catch (e) {
                    console.error(`Error processing block ${opcode}:`, e);
                }

                // Helper to get a clean value for any input
                const getVal = (name) => this.resolveInput(block, name, target);

                switch (opcode) {
                    case `${extension_id}_setMetaData`:
                    case `${extension_id}_setMetaDataBlocks`:
                        const tag = block.fields.METATAG.value;
                        const val = getVal('VALUE');
                        // Formatting for your JSON/Object view
                        lines.push(`  ${tag}: ${val},`);
                        break;

                    case `${extension_id}_createListItem`:
                        lines.push(` {`);
                        lines.push(`  text: ${getVal('NAME')},`);
                        lines.push(`  value: ${getVal('VALUE')}`);
                        lines.push(`},`);
                        break;

                    case `${extension_id}_getArgumentValue`:
                        const argName = getVal('NAME').replaceAll('"', ''); // Remove quotes if it's a string
                        return `args.${argName}`; // This allows users to get the value of an argument in their code blocks by using the "get value of argument" block and specifying the argument name.
                        break;

                    case `${extension_id}_generateExtensionMetaData`:
                        let blockHats = this.getAllHats('defineExtensionBlock', allBlocks); // Get all hats that define block functions
                        let menuHats = this.getAllHats('defineExtensionMenus', allBlocks); // Get all hats that define block functions

                        let blocks = this.getHatCode(blockHats, allBlocks, target);
                        let menuBlocks = this.getHatCode(menuHats, allBlocks, target);

                        let sendingCode = `blocks: [\n${blocks}\n],\nmenus: {\n${menuBlocks}\n},\n`; // This is the code that will be injected into the extension metadata. It includes both the blocks and the menus.
                        this.buildDefinition(block.fields.DEFINITIONTYPE.value, lines, substackId, target, sendingCode);
                        break;

                    case `${extension_id}_generateBlockMetaData`:
                        const definitionType = block.fields.DEFINITIONTYPE.value;

                        this.buildDefinition(definitionType, lines, substackId, target);
                        break;

                    case `${extension_id}_generateMenu`:
                        const menuName = getVal('MENUNAME');

                        this.buildDefinition('menu', lines, substackId, target, menuName);
                        break;

                    case `${extension_id}_buildBlockType`:
                        lines.push(block.fields.TYPE.value);
                        break;

                    case `${extension_id}_defineArguments`:
                        let arg_type = block.fields.TYPE.value;
                        let arg_default = getVal('DEFAULT');
                        let arg_name = getVal('NAME');
                        let type = block.fields.INPUT.value;

                        lines.push(arg_name + `: {`);
                        lines.push(`  type: ${arg_type},`);
                        lines.push(`  ${type}: ${arg_default}`);
                        lines.push(`},`);
                        break;

                    case `${extension_id}_checkFunctionAvailability`:
                        const functionName = getVal('NAME');
                        lines.push(`!String(this.runtime.getOpcodeFunction('${functionName}')) === 'undefined'\n`);
                        break;

                    case `${extension_id}_executeBranchBlocks`:
                        const actionType = block.fields.ACTIONTYPE.value; // "loop" or "execute"
                        const branchNumber = getVal('BRANCHNUMBER'); // 1, 2, or 3

                        lines.push(`util.startBranch(${branchNumber}, ${actionType == 'loop'});`); // Start the specified branch

                        break;
                    default:
                        const scratchVMTarget = Scratch.vm.runtime.getEditingTarget();

                        if (this.presetCode.includes(`this.${opcode} =`)) break; // If the preset code already contains this opcode, skip it to avoid duplicates

                        this.presetCode += `this.${opcode} = this.runtime.getOpcodeFunction('${opcode}');\n`;
                        // remove all "" so that functions will still work.
                        lines.push(`
                            await this.${opcode}(${this.getBlockArguments(block, target).replaceAll('"', ' ')}, util);
                            `);
                }

                currentId = target.blocks.getNextBlock(currentId);
            }
            return lines.join('\n');
        }

        isReporter(opcode) {
            // Get the block definition from the runtime
            const blockDef = Scratch.vm.runtime.getBlocksXML().find(b => b.opcode === opcode);

            // Check if it's a reporter (round) or a boolean (hexagonal)
            // These are the blocks that return values rather than executing 'next' blocks
            return blockDef && (blockDef.blockType === 'reporter' || blockDef.blockType === 'boolean');
        }

        getBlockArguments(block, target) {
            const args = {};
            for (const inputName in block.inputs) {
                const input = block.inputs[inputName];

                // Check if the input is a simple value (shadow) or another block (reporter)
                if (input.shadow && !input.block) {
                    // It's a direct value like a number or string
                    const value = target.blocks.getBlock(input.shadow).fields.VALUE.value;
                    args[inputName] = JSON.stringify(value); // JSON.stringify adds quotes to strings automatically
                } else if (input.block) {
                    // It's a nested reporter block (e.g., 'distance to mouse')
                    // You would recursively call a 'generateCode' function here
                    let transpiledCode = this.transpile(input.block, target).replaceAll('\n', '').trim(); // Recursively transpile the nested block and clean up the code
                    if (transpiledCode[0] === '"' && transpiledCode[transpiledCode.length - 1] === '"') {
                        transpiledCode = transpiledCode.replaceAll('"', "'"); // Convert double quotes to single quotes for string literals to avoid issues in the generated code when "" are removed
                    }
                    args[inputName] = transpiledCode.replace(';', ''); // remove semicolons to avoid issues in the generated code when ";" are removed. This is a bit hacky but it allows users to write blocks that return values without worrying about semicolons breaking their code.
                    console.log(transpiledCode);
                }
            }
            return JSON.stringify(args); // Convert the args object to a string for code generation
        }

        // injectionBlocks is a string that contains the code for the blocks that should be injected into the extension metadata or anywhere else.

        buildDefinition(definitionType, lines, substackId, target, injectionBlocks = '') {
            switch (definitionType) {
                case 'emd':
                    lines.push(`  getInfo() {`);
                    lines.push(`    return {`);
                    if (substackId) lines.push(this.transpile(substackId, target));

                    lines.push(injectionBlocks); // Add the generated blocks code to the extension metadata

                    lines.push(`    };`);
                    lines.push(`  }`);
                    break;

                case 'bmd':
                    lines.push(`{`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`}`);
                    break;

                case 'menu':
                    lines.push(injectionBlocks + ` :{`); // reuse injectionBlocks here just for menu names.
                    lines.push('acceptReporters: false,'); // Allows users to drop a round block into the menu
                    lines.push(`items: [`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`]`);
                    lines.push(`}`);
                    break;

                case 'bargs':
                    lines.push(`arguments: {`);
                    if (substackId) lines.push(this.transpile(substackId, target));
                    lines.push(`}`);
                    break;

                default:
                    lines.push(`// Unknown definition type: ${definitionType}`);
            }
        }

        resolveInput(parentBlock, inputName, target) {
            const input = parentBlock.inputs[inputName];
            if (!input || !input.block) return 'null';

            const inputBlock = target.blocks.getBlock(input.block);

            // 1. Check for Shadow Blocks (Simple inputs)
            // Opcode 'text' is the white bubble for strings
            // Opcode 'math_number' is the white bubble for numbers
            if (inputBlock.opcode === 'text') {
                return `"${inputBlock.fields.TEXT.value}"`;
            }
            if (inputBlock.opcode === 'math_number') {
                return inputBlock.fields.NUM.value;
            }

            // 2. Check for Reporter Blocks (e.g. "x position", "my variable")
            // If it's a real block, transpile it to get its "code" representation
            return this.transpile(input.block, target).trim();
        }

        updateCode(args, util) {
            const target = util.target;
            const allBlocks = target.blocks._blocks;

            let pre_production_code = '';

            this.presetCode = ''; // Reset preset code on each update to avoid duplicates

            // 1. Find our "Define" Hat block in the workspace
            let hatId = null;
            let opcode_hats = this.getAllHats('defineBlockFunction', allBlocks); // Get all hats that define block functions
            for (const id in allBlocks) {
                if (allBlocks[id].opcode === `${extension_id}_defineExtensionHat`) {
                    if (!hatId) {
                        hatId = id;
                    }
                }
            }

            if (!hatId) {
                this.generatedCode = "// Please place the 'define' hat block!";
                return;
            }

            // 2. Get the name from the hat block's inputs
            const nameBlockId = allBlocks[hatId].inputs.NAME.block;
            const extensionName = allBlocks[nameBlockId].fields.TEXT.value || "MyExtension";

            // 3. Generate the class string
            const body = this.transpile(target.blocks.getNextBlock(hatId), target); // pass the hat id here instead of in the transpile function so we ca nreuse the transpile function

            let opcode_body = this.getHatCode(opcode_hats, allBlocks, target); // Generate code for all opcode hats

            pre_production_code = `
            class ${extensionName} {
            constructor(runtime) {
            this.runtime = runtime;
            ${this.presetCode}
            }

            ${body}
              
            ${opcode_body}
            }
            Scratch.extensions.register(new ${extensionName}(Scratch.vm.runtime));`;

            if(pre_production_code === this.generatedCode) return; // If the generated code is the same as the previous generated code, don't log it again to avoid spamming the console with duplicate code.

            this.generatedCode = pre_production_code; // Store the generated code in a variable so we can compare it on the next update to avoid duplicates.
            console.log(pre_production_code);
        }

        getAllHats(opcode, allBlocks) { // gets all hats with the specified opcode
            let hats = [];
            for (const id in allBlocks) {
                if (allBlocks[id].opcode === `${extension_id}_${opcode}`) {
                    hats.push(id);
                }
            }
            return hats;
        }

        getHatCode(hats, allBlocks, target) { // gets all the code for the list of the hats provided
            let code = '';
            hats.forEach(hatId => {
                try {
                    const opcode_name_block_id = allBlocks[hatId].inputs.OPCODENAME.block;
                    const opcode_name = allBlocks[opcode_name_block_id].fields.TEXT.value || "opcode_name";

                    const hat_body = this.transpile(target.blocks.getNextBlock(hatId), target);
                    code += `\n async ${opcode_name} (args, util) {\n${hat_body}\n  }\n`;
                } catch (e) {
                    const hat_body = this.transpile(target.blocks.getNextBlock(hatId), target);
                    code += hat_body + ',\n';
                }
            });

            return code;
        }

        defineExtensionHat(args, util) {
            this.updateCode(args, util); // allows the user to press the green flag to update and print the generated code.
        }

    }

    class ExtensionBlockDefinitions {
        constructor(runtime) { }

        getInfo() {
            return {
                id: extension_id,
                name: 'Extension Block Definitions Blocks',
                color1: '#5c9ba5', // Main block color
                blocks: [
                    {
                        opcode: 'defineExtensionBlock',
                        blockType: Scratch.BlockType.HAT,
                        text: 'define extension block',
                    },
                    {
                        opcode: 'defineExtensionMenus',
                        blockType: Scratch.BlockType.HAT,
                        text: 'define extension menus',
                    },
                    {
                        opcode: 'generateBlockMetaData',
                        blockType: Scratch.BlockType.CONDITIONAL,
                        text: 'Define [DEFINITIONTYPE]',
                        branchCount: 1, // This is the magic property
                        arguments: {
                            DEFINITIONTYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'definitionTypes' // Must match the key in the menus object
                            }
                        }
                    },
                    {
                        opcode: 'generateMenu',
                        blockType: Scratch.BlockType.CONDITIONAL,
                        text: 'Define [MENUNAME]',
                        branchCount: 1, // This is the magic property
                        arguments: {
                            MENUNAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Menu Name'
                            }
                        }
                    },
                    {
                        opcode: 'defineArguments',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'Define argument [NAME] as [TYPE] with [INPUT] [DEFAULT]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Argument Name'
                            },
                            TYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'argumentTypes' // Must match the key in the menus object
                            },
                            DEFAULT: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            },
                            INPUT: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'argumentDropdownTypes' // Must match the key in the menus object
                            }
                        }
                    },
                    {
                        opcode: 'buildBlockType',
                        blockType: Scratch.BlockType.REPORTER,
                        text: 'block type[TYPE]',
                        arguments: {
                            TYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'blockTypes' // Must match the key in the menus object
                            }
                        }
                    },
                    {
                        opcode: 'setMetaDataBlocks',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'set [METATAG] to [VALUE]',
                        arguments: {
                            METATAG: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'metaData' // Must match the key in the menus object
                            },
                            VALUE: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            }
                        }
                    },
                    {
                        opcode: 'createListItem',
                        blockType: Scratch.BlockType.COMMAND,
                        text: 'create item with [NAME] and value [VALUE]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Item Name'
                            },
                            VALUE: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'Default Value'
                            }
                        }
                    },
                ],
                menus: {
                    blockTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Command', value: 'Scratch.BlockType.COMMAND' },
                            { text: 'Reporter', value: 'Scratch.BlockType.REPORTER' },
                            { text: 'Boolean', value: 'Scratch.BlockType.BOOLEAN' },
                            { text: 'Conditional', value: 'Scratch.BlockType.CONDITIONAL' },
                            { text: 'Loop', value: 'Scratch.BlockType.LOOP' },
                            { text: 'Hat', value: 'Scratch.BlockType.HAT' },
                            { text: 'Event', value: 'Scratch.BlockType.EVENT' }
                        ]
                    },
                    argumentTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'String', value: 'Scratch.ArgumentType.STRING' },
                            { text: 'Number', value: 'Scratch.ArgumentType.NUMBER' },
                            { text: 'Boolean', value: 'Scratch.ArgumentType.BOOLEAN' }
                        ]
                    },
                    metaData: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Function', value: 'opcode' },
                            { text: 'Type', value: 'blockType' },
                            { text: 'Text', value: 'text' },
                            { text: 'Branch Count', value: 'branchCount' },
                        ]
                    },
                    argumentDropdownTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Default Value', value: 'defaultValue' },
                            { text: 'Menu', value: 'menu' },
                        ]
                    },
                    definitionTypes: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Block meta data', value: 'bmd' },
                            { text: 'Block arguments', value: 'bargs' },
                        ]
                    }
                }
            };
        }

        defineExtensionMenus() {
            return false;
        }

        generateMenu() {
            return false;
        }

        generateBlockMetaData() {
            return false; // The actual generation of the block meta data is handled in the generated code, this block just serves as a trigger for users to indicate they want to generate block meta data and to specify which type of meta data they want to generate.
        }

        defineExtensionBlock() {
            return false;
        }

    }

    class extensionCodeBlocks {
        constructor(runtime) { }

        getInfo() {
            return {
                id: extension_id,
                name: 'Extension Code Blocks',
                color1: '#725ca5', // Main block color
                blocks: [
                    {
                        opcode: 'defineBlockFunction',
                        blockType: Scratch.BlockType.HAT,
                        text: 'Define block opcode [OPCODENAME]',
                        arguments: {
                            OPCODENAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'opcode_name'
                            }
                        }
                    },
                    {
                        opcode: 'getArgumentValue',
                        blockType: Scratch.BlockType.REPORTER,
                        text: 'get value of argument[NAME]',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'ARGUMENTNAME'
                            }
                        }
                    },
                    {
                        opcode: 'checkFunctionAvailability',
                        blockType: Scratch.BlockType.BOOLEAN,
                        text: 'check if function [NAME] is available',
                        arguments: {
                            NAME: {
                                type: Scratch.ArgumentType.STRING,
                                defaultValue: 'ARGUMENTNAME'
                            }
                        }
                    },
                    {
                        opcode: 'executeBranchBlocks',
                        blockType: Scratch.BlockType.COMMAND,
                        text: "[ACTIONTYPE] branch [BRANCHNUMBER]'s blocks",
                        arguments: {
                            ACTIONTYPE: {
                                type: Scratch.ArgumentType.STRING,
                                menu: 'loopBranch' // Must match the key in the menus object
                            },
                            BRANCHNUMBER: {
                                type: Scratch.ArgumentType.NUMBER,
                                defaultValue: 1
                            }
                        }
                    }
                ],
                menus: {
                    loopBranch: {
                        acceptReporters: false, // Allows users to drop a round block into the menu
                        items: [
                            { text: 'Loop', value: 'loop' },
                            { text: 'Execute', value: 'execute' },
                        ]
                    },
                }
            };
        }

        executeBranchBlocks() {
            return false; // The actual execution of the blocks is handled in the generated code, this block just serves as a trigger for users to indicate they want to execute branch blocks and to specify which branch number they want to execute.
        }

        checkFunctionAvailability() {
            return false;
        }

        defineBlockFunction() {
            return false;
        }

    }

    Scratch.extensions.register(new ExtensionDefinitionBlocks());
    Scratch.extensions.register(new ExtensionBlockDefinitions());
    Scratch.extensions.register(new extensionCodeBlocks());
})(Scratch);    